### ISSUE TITLE
Huge Lag Spike on Autosave

### ISSUE THREAD

**Issue by designsbyaustin** [sleepingdragoninn/surveyor#18]
Hey!

First, I wanted to say I love your mod as well as Atlas 4. I really enjoy the stylized map so thank you for that!

I ran into an issue where surveyor is increasing the autosave tick time by over 1000ms, which causes the server to stop and skip forward very harshly. I have attached two spark profilers, one is with surveyor, and one without. It increases the lag from a 300ms tick to a 1600ms tick.

I uninstalled it from the server so I can still use the map, but my friend and I can't see each other on the map anymore.

With Surveyor: https://spark.lucko.me/x4lylCfp4U

Without: https://spark.lucko.me/7HV7AGHJvh

**Comment by sleepingdragoninn** [comment]
Thanks for the report! And i'm glad to hear people are having success with map sharing / friend position sharing.

Out of curiosity, what command are you running to get a nice profile of the save process? We've noticed a fairly hefty increase in load and save times with large surveyor save files (it _is_ a lot of data, to be fair - just compressed), but haven't had a good way to profile the load hang.

**Comment by sleepingdragoninn** [comment]
From observation, the structure saving is taking the most time - this makes sense, because it's a single file with no partial save support. If you could send me your `data/structures.dat` from the server that'd be helpful as well.

**Comment by designsbyaustin** [comment]
Yes! The player location sharing is AMAZING on Atlas. The fact that you can see each other no matter how far away they are is brilliant. I don't think Xaeros even does that. I was thinking, maybe the server could just be utilized to share location and map markers, and everything else could have an option to be turned off? Maybe that would reduce this problem (I'm not a programmer I have no idea)

With the structures, thats interesting because my friend and I haven't seen a single structure populate on our map. We are using a heavily modded minecraft and so the map doesn't recognize any of the improved structures, since I haven't bothered to add them in the config.

[structures.zip](https://github.com/sisby-folk/surveyor/files/15195078/structures.zip)

As for the profiler, I followed this wonderful guide on it here:

https://spark.lucko.me/docs/guides/Finding-lag-spikes

I used the command: /spark profiler --only-ticks-over 300

Let me know if there's any other testing I can do to help!

**Comment by sleepingdragoninn** [comment]
Your notes about not seeing structures makes sense! Plenty of stuff here that wouldn't match - you'd only be getting village variants, outside of vanilla stuff.

![image](https://github.com/sisby-folk/surveyor/assets/55819817/f106609c-c53e-467f-8021-7e355f03ab6e)

Thanks for the tip on spark, we definitely should've bothered to read the docs lmao

We can definitely resolve this by smashing the structure save format to be per-region instead of one big `structures.dat` - because structures are uneditable, that should mean only the first exploration of a region will ever cause structure saves, cutting down on the structure save time by a factor of 100-1000ish.

We'll need to retain a reader for the old format for compatibility, and we'll try hunt down other saving slowdowns first - will release as surveyor 0.4 and AA 2.7.1 once it's done!

**Comment by designsbyaustin** [comment]
Thank you for the coming update, I can't wait to add this back into the server!

For the config structures list, could I just copy all of those structures and paste them into the AA config with = true? I read on the AA Modrinth page that modded structures could be linked to vanilla structure tiles with an mcmeta file. Is that something I could do fairly easily or would that require coding knowledge?

**Comment by sleepingdragoninn** [comment]
The config is there so you can turn off structures you don't like - to _add_ structures, you've gotta create a resource pack.

There's a section in the readme, but I'll assume you know respack basics and give you a towers of the wild modded example, seeing as that's in your list.

TOTW modded is visible source and a datapack packaged as a mod, so the first thing I did was open up their [resources](https://github.com/celsiusqc/TowersOfTheWildModded/tree/1.20.1/src/main/resources/data/totw_modded/structures) and check if they register some kind of structure tag we can use to identify all towers at once.

They don't, so that means we have to register markers for _every_ tower using structure IDs - annoying, but doable. We can see there's a structure with the ID `totw_modded:derilect` based on the directories, so we'd add a file `assets/totw_modded/atlas/structure/start/derilect.json` to our respack folder, open it with a text editor, and add:

```json
{
  "markers": "antique_atlas:structure/bastion_remnant"
}
```

then, we add a file `assets/{anything}/lang/en_us.json` with:

```json
  "structure.start.totw_modded.derilect": "Derilect Wild Tower",
```

Add a pack.mcmeta, zip it up, load it in your instance, and you should see a marker using the [bastion remnant](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/marker/structure/bastion_remnant.png) atlas texture for all derilect wild towers - naturally you can add your own texture too.

Rinse and repeat the middle steps to assign the other 21 structures, and you're golden. Or beg the totw_modded dev to add a structure tag, then you can just have one marker for all of them. Realistically, this is just an example, and i'm guessing you use surveystones markers to see where towers are indirectly anyway - so maybe you'd prefer a tile instead of a marker, who knows!

We're planning on starting a repo for all compat packs once someone submits the first one, so feel free to send anything you make our way.

**Comment by sleepingdragoninn** [comment]
I've put out 0.3.5 which fixes an oversight that caused _all_ saves to lag after adding a structure, instead of just saves where the structure save has actually been updated https://modrinth.com/mod/surveyor/version/0.3.5+1.20 feel free to check this doesn't break anything if you have spare time.

I'll move onto the reformat now.

**Comment by designsbyaustin** [comment]
Thank you so much. That does seem like a daunting task, but I will try and make some markers.

I will test that new update right now.

**Comment by sleepingdragoninn** [comment]
Ah and I don't think you'll have issues in 0.3.5, but for 0.4 make sure you take a backup of your world - I could easily accidentally wipe your surveyor structure data if I set it up wrong (though you did just send me a copy)

**Comment by designsbyaustin** [comment]
Okay, I will backup my save before updating to 0.4.

This update seems to have solved it, but I'll be on the server with my friend tonight so I can test much more extensively.

It was a 308ms save tick this time. Very much improved. Thank you for the quick fix.

https://spark.lucko.me/KrAU1QaR7f

**Comment by designsbyaustin** [comment]
Edit: I think there may have been a save tick that was 600ms before the 308, so that's why I'm going to test more to figure that out. But still, very much improved from 1600 lmaoo

**Comment by sleepingdragoninn** [comment]
That makes sense - you should still get quite slow saves - just less often. Thanks for the new profile!

**Comment by sleepingdragoninn** [comment]
(removed - checked this myself and it looks fine)

**Comment by sleepingdragoninn** [comment]
That took way less time than I thought it was going to - @designsbyaustin could you try out 0.4.0 now? https://modrinth.com/mod/surveyor/version/0.4.0+1.20

**Comment by designsbyaustin** [comment]
Wow that was fast! I am online with my friend, so I will put that on the server after backing it up. Will test it in a couple hours.

**Comment by sleepingdragoninn** [comment]
bonus - in the new version, the contents of the `structures.dat` file is now very short, so it can be more easily used to read all of the structure IDs and tags, for the purposes of making resource packs - just pop it into any NBT editor.
![image](https://github.com/sisby-folk/surveyor/assets/55819817/6c86385b-c96d-44c2-8674-e128a4b3174e)

**Comment by designsbyaustin** [comment]
The results are in:

https://spark.lucko.me/F8stUN41qb

It's completely fixed, not a single tick went over the normal autosave rate. Thank you!

Also, what NBT editor do you use? I've never used one before and that one looks very clean.

**Comment by sleepingdragoninn** [comment]
I'm cheating a bit - this is Intellij IDEA community with the minecraft development plugin - it's not very good for large files (it gets very laggy) but it's okay for smaller ones. NBTExplorer is old but it works fine, unbted is good if you're really into CLI.

Thanks for testing this out for us!
